Repository ovn-org/libovsdb, pull requests merged in 2021-07, with the labels that each got.

#182 cache: Return IndexExistsError immediately
  cache/cache.go
  cache/cache_test.go
  server/server_integration_test.go
Labels: fix

#176 Auto reconnect
  cache/cache.go
  client/client.go
  client/client_test.go
  client/options.go
  client/options_test.go
  cmd/stress/stress.go
  example/play_with_ovs/play_with_ovs.go
  go.mod
  go.sum
  server/server_integration_test.go
  test/ovs/ovs_integration_test.go
Labels: feature

#174 client: Speed up row access by index
  cache/cache.go
  cache/cache_test.go
  client/api.go
Labels: feature

#185 Fix: output dir was not used in modelgen
  cmd/modelgen/main.go
Labels: fix

#184 ovsdb: remove interfaceToOVSDBNotationInterface
  ovsdb/condition.go
  ovsdb/encoding_test.go
  ovsdb/map.go
  ovsdb/mutation.go
  ovsdb/notation.go
  ovsdb/notation_test.go
  ovsdb/set.go
Labels: fix

#186 cache: Disable Index Checking on Populate
  cache/cache.go
  cache/cache_test.go
  server/database.go
Labels: fix

#194 api: fix update is using wrong 'op'
  client/api.go
  client/api_test.go
Labels: fix

#200 Makefile: Add missing dependency to test target
  Makefile
Labels: test

#199 server: delay transact commit
  cache/cache.go
  cache/cache_test.go
  server/database.go
  server/errors.go
  server/monitor.go
  server/mutate.go
  server/server.go
  server/server_integration_test.go
  server/server_test.go
  server/transact.go
  server/transact_test.go
Labels: feature

#202 server: Fix Update Operation
  cache/cache.go
  server/database.go
  server/server_integration_test.go
  server/transact.go
  test/ovs/ovs_integration_test.go
Labels: fix
